In [15]:
#import libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
#import dataset

ds=pd.read_csv("raw_messy_dataset.csv")

In [3]:
ds.describe()

Name Age Gender              Email   Join_Date Salary   Department
count     105  72     89                 95          70     78           89
unique     10   5      5                 90           4      5            5
top     Alice  40   Male  user0@example.com  2021-05-21  50000  Engineering
freq       11  22     22                  2          26     22           26

In [6]:
print(ds.to_string())

        Name      Age  Gender               Email     Join_Date   Salary   Department
0      Alice      NaN     NaN   user0@example.com    2021-05-21      NaN        Admin
1        Bob       40       M   user1@example.com           NaN    50000  Engineering
2    Charlie  unknown    Male   user2@example.com    2020/01/01    50000           HR
3      David      NaN     NaN   user3@example.com    2021-05-21    70000        Admin
4        Eva       35   Other   user4@example.com  July 4, 2020    70000  Engineering
5      Frank  unknown   Other   user5@example.com           NaN    70000        Admin
6      Grace  unknown  Female   user6@example.com  July 4, 2020    80000  Engineering
7     Hannah      NaN   Other   user7@example.com    2021-05-21      NaN           HR
8        Ivy       30  Female   user8@example.com           NaN    50000  Engineering
9       Jack       35    Male   user9@example.com    2020/01/01    80000  Engineering
10     Alice      NaN       M  user10@example.com    2

In [7]:
ds.duplicated().sum()

np.int64(5)

In [8]:
ds.drop_duplicates(inplace=True)

In [9]:
ds.duplicated().sum()

np.int64(0)

In [11]:
ds['Age']=pd.to_numeric(ds['Age'],errors='coerce')

In [12]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Name        100 non-null    object 
 1   Age         57 non-null     float64
 2   Gender      86 non-null     object 
 3   Email       90 non-null     object 
 4   Join_Date   66 non-null     object 
 5   Salary      74 non-null     object 
 6   Department  84 non-null     object 
dtypes: float64(1), object(6)
memory usage: 6.2+ KB


In [16]:
x=ds['Age'].median()
ds['Age'].fillna(x,inplace=True)

In [17]:
ds["Age"].unique()

array([35., 40., 30., 25.])

In [18]:
ds['Gender'].unique()

array([nan, 'M', 'Male', 'Other', 'Female', 'F'], dtype=object)

In [19]:
ds['Gender']=ds['Gender'].replace(
    {
        "M":"Male",
        "F":"Female",
        "":"None"
    })

In [20]:
ds['Gender'].unique()

array([nan, 'Male', 'Other', 'Female'], dtype=object)

In [21]:
ds['Email'].fillna("-",inplace=True)

In [23]:
print(ds.to_string())

       Name   Age  Gender               Email     Join_Date   Salary   Department
0     Alice  35.0     NaN   user0@example.com    2021-05-21      NaN        Admin
1       Bob  40.0    Male   user1@example.com           NaN    50000  Engineering
2   Charlie  35.0    Male   user2@example.com    2020/01/01    50000           HR
3     David  35.0     NaN   user3@example.com    2021-05-21    70000        Admin
4       Eva  35.0   Other   user4@example.com  July 4, 2020    70000  Engineering
5     Frank  35.0   Other   user5@example.com           NaN    70000        Admin
6     Grace  35.0  Female   user6@example.com  July 4, 2020    80000  Engineering
7    Hannah  35.0   Other   user7@example.com    2021-05-21      NaN           HR
8       Ivy  30.0  Female   user8@example.com           NaN    50000  Engineering
9      Jack  35.0    Male   user9@example.com    2020/01/01    80000  Engineering
10    Alice  35.0    Male  user10@example.com    2021-05-21    70000  Engineering
11      Bob  35.

In [24]:
ds['Join_Date']=pd.to_datetime(ds['Join_Date'],errors='coerce')

In [25]:
ds['Salary']=pd.to_numeric(ds['Salary'],errors='coerce')

In [26]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   Name        100 non-null    object        
 1   Age         100 non-null    float64       
 2   Gender      86 non-null     object        
 3   Email       100 non-null    object        
 4   Join_Date   24 non-null     datetime64[ns]
 5   Salary      60 non-null     float64       
 6   Department  84 non-null     object        
dtypes: datetime64[ns](1), float64(2), object(4)
memory usage: 6.2+ KB


In [27]:
ds['Department'].unique()

array(['Admin', 'Engineering', 'HR', 'Sales', nan, 'Marketing'],
      dtype=object)

In [28]:
y=ds['Department'].mode()[0]
ds['Department'].fillna(y,inplace=True)

In [29]:
ds.to_csv("Cleaned_data_pr1.csv")

In [31]:
ds2=pd.read_csv("Cleaned_data_pr1.csv")
print(ds2.to_string())

    Unnamed: 0     Name   Age  Gender               Email   Join_Date   Salary   Department
0            0    Alice  35.0     NaN   user0@example.com  2021-05-21      NaN        Admin
1            1      Bob  40.0    Male   user1@example.com         NaN  50000.0  Engineering
2            2  Charlie  35.0    Male   user2@example.com         NaN  50000.0           HR
3            3    David  35.0     NaN   user3@example.com  2021-05-21  70000.0        Admin
4            4      Eva  35.0   Other   user4@example.com         NaN  70000.0  Engineering
5            5    Frank  35.0   Other   user5@example.com         NaN  70000.0        Admin
6            6    Grace  35.0  Female   user6@example.com         NaN  80000.0  Engineering
7            7   Hannah  35.0   Other   user7@example.com  2021-05-21      NaN           HR
8            8      Ivy  30.0  Female   user8@example.com         NaN  50000.0  Engineering
9            9     Jack  35.0    Male   user9@example.com         NaN  80000.0  